name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore src\FindDuplicateBookings.sln
    - name: Build
      run: dotnet build src\FindDuplicateBookings.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src\FindDuplicateBookings.sln --no-build --verbosity normal --configuration Release /p:CollectCoverage=true
